
UPDATE cdn_scripts
SET content = REPLACE(
  content,
  E'loadBtn.addEventListener(\'click\', function() {\n            loadBtn.disabled = true;\n            loadBtn.innerHTML = \'<span>⏳</span> Carregando...\';\n            resultDiv.innerHTML = \'\';\n\n            // Get selected instance ID from bridge-switcher dropdown\n            var switcherSelect = document.getElementById(\'bridge-instance-selector\');\n            var selectedInstanceId = switcherSelect ? switcherSelect.value : null;\n\n            var bodyPayload = { groupjid: groupjid };',
  E'loadBtn.addEventListener(\'click\', function() {\n            var groupjid = extractGroupJid();\n            var locationId = extractLocationId();\n\n            if (!groupjid || !/^\\d+@g\\.us$/.test(groupjid)) {\n                resultDiv.innerHTML = \'<div style=\"padding:16px;background:#fef3c7;border:1px solid #fcd34d;border-radius:10px;color:#92400e;font-size:13px;text-align:center;\">⚠️ <strong>Você precisa estar dentro de um grupo e ser admin do grupo.</strong><br>Verifique se o campo de email do contato contém o JID do grupo (ex: 120363...@g.us).</div>\';\n                return;\n            }\n\n            if (!locationId) {\n                resultDiv.innerHTML = \'<div style=\"padding:16px;background:#fef3c7;border:1px solid #fcd34d;border-radius:10px;color:#92400e;font-size:13px;text-align:center;\">⚠️ Não foi possível identificar a subconta na URL.</div>\';\n                return;\n            }\n\n            loadBtn.disabled = true;\n            loadBtn.innerHTML = \'<span>⏳</span> Carregando...\';\n            resultDiv.innerHTML = \'\';\n\n            // Get selected instance ID from bridge-switcher dropdown\n            var switcherSelect = document.getElementById(\'bridge-instance-selector\');\n            var selectedInstanceId = switcherSelect ? switcherSelect.value : null;\n\n            var bodyPayload = { groupjid: groupjid };'
),
updated_at = now()
WHERE slug = 'bridge-button-beta.js';
